apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: qinjunjerrypipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: qinjunjerrypipelinesjavascriptdocker 
    spec:
      containers:
        - name: qinjunjerrypipelinesjavascriptdocker 
          image: jqincontainerregistry.azurecr.io/qinjunjerrypipelinesjavascriptdocker
          ports:
          - containerPort: 8080